export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PALETTE = 'UPDATE_PALETTE';
export const UPDATE_STREAK = 'UPDATE_STREAK';
export const NO_DATA_STREAK = 'NO_DATA_STREAK';
export const NO_DATA_PALETTE = 'NO_DATA_PALETTE';
export const DESTROY_STATE = 'DESTROY_STATE';
